server:
  port: 8888
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    connection-timeout: 30000

spring:
  application:
    name: message-queue-chat-backend
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://mysql-service.default.svc.cluster.local:3306/message_queue_chat?autoReconnect=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&cacheDefaultTimeZone=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"

    hikari:
      maximum-pool-size: 5
      maxLifeTime: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  kafka:
    broker: kafka-service.default.svc.cluster.local:9092

logging:
  level:
    ROOT: info
    org:
      springframework:
        web: error

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:3000,http://localhost:31733,*